In [1]:
import numpy as np

In [2]:
l  = [1,2,3,4]

In [3]:
arr = np.array(l)

In [4]:
l+10

TypeError: can only concatenate list (not "int") to list

In [5]:
arr+10

array([11, 12, 13, 14])

In [6]:
arr-10

array([-9, -8, -7, -6])

In [7]:
arr * 2

array([2, 4, 6, 8])

In [8]:
arr ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [9]:
l ** 2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [10]:
l1 = [1, 2, 3, 'string_test', 1.1]

In [12]:
arr1 = np.array(l1)
arr1

array(['1', '2', '3', 'string_test', '1.1'], dtype='<U11')

In [14]:
range(1.5, 10.5)
# range can be only integers

TypeError: 'float' object cannot be interpreted as an integer

In [17]:
arr2 = np.arange(1.5, 10.5, 0.2)
arr2

array([ 1.5,  1.7,  1.9,  2.1,  2.3,  2.5,  2.7,  2.9,  3.1,  3.3,  3.5,
        3.7,  3.9,  4.1,  4.3,  4.5,  4.7,  4.9,  5.1,  5.3,  5.5,  5.7,
        5.9,  6.1,  6.3,  6.5,  6.7,  6.9,  7.1,  7.3,  7.5,  7.7,  7.9,
        8.1,  8.3,  8.5,  8.7,  8.9,  9.1,  9.3,  9.5,  9.7,  9.9, 10.1,
       10.3])

In [20]:
arr3 = np.arange(1,11,0.1)
arr3

array([ 1. ,  1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,
        2.1,  2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,
        3.2,  3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,
        4.3,  4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,
        5.4,  5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,
        6.5,  6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,
        7.6,  7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,
        8.7,  8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,
        9.8,  9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8,
       10.9])

In [21]:
len(arr3)
# instead of using arange for getting 100 elements we can use linspace

100

In [23]:
arr4 = np.linspace(1,10,100)
arr4

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [24]:
len(arr5)

NameError: name 'arr5' is not defined

In [26]:
array_of_zeros = np.zeros((2,3))
array_of_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
arr_of_ones = np.ones((2,3,4))
arr_of_ones


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [30]:
arr_linspace = np.linspace(0,2)
arr_linspace

array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
       0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
       0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
       0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
       0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
       1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
       1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
       1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
       1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
       1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ])

In [31]:
arr_linspace_in_10 = np.linspace(0,2,9)
arr_linspace_in_10

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [33]:
arr_full = np.full((2,2),7)
arr_full

array([[7, 7],
       [7, 7]])

In [35]:
f = np.eye(2) # identity matrix
f

array([[1., 0.],
       [0., 1.]])

In [37]:
r = np.random.random((2,2)) # only positive values are retrived randomly
r

array([[0.81972969, 0.15798756],
       [0.53223683, 0.96036838]])

In [45]:
r1 = np.random.random((2,3))
r1

array([[0.94055815, 0.5406822 , 0.19076485],
       [0.39016225, 0.39836948, 0.86462899]])

In [46]:
r2 = np.random.randn(2,3) # negative integers are also considered along with the single paranthesis
r2

array([[ 1.12481759,  1.69581681, -0.11519515],
       [ 1.42351453, -0.13569349, -1.51901421]])

In [51]:
# specific range 
r3 = np.random.randint(40,98,size=(5, 5))
r3

array([[59, 92, 74, 50, 54],
       [73, 70, 58, 40, 49],
       [65, 81, 77, 95, 49],
       [72, 70, 47, 72, 94],
       [65, 79, 50, 52, 55]])

In [53]:
# specific range 
r4 = np.random.randint(0, 20, size=(1000,20))
r4

array([[18,  0, 11, ..., 16,  8, 19],
       [ 9,  1, 16, ..., 10, 13, 18],
       [13, 14,  5, ...,  1, 14,  8],
       ...,
       [16, 12,  0, ..., 18,  9,  7],
       [12, 13, 18, ..., 10,  7,  6],
       [10, 13, 10, ..., 14,  1,  8]])

In [54]:
r5 = np.random.choice(list("kris"))
r5

's'

In [55]:
r6 = np.random.choice(list("test string"))
r6

'i'

In [62]:
# shuffle the original position of the elements of an array
arr9 = np.random.randint(40,90, size=(5,5))
print(arr9)


[[63 44 80 44 79]
 [89 44 58 69 78]
 [51 87 68 53 84]
 [54 41 73 48 54]
 [70 68 47 84 66]]


In [66]:
np.random.shuffle(arr9)
arr9

array([[54, 41, 73, 48, 54],
       [89, 44, 58, 69, 78],
       [51, 87, 68, 53, 84],
       [70, 68, 47, 84, 66],
       [63, 44, 80, 44, 79]])