In [1]:
import numpy as np

In [3]:
l = [1,2,3,4]

In [4]:
arr = np.array(l)

In [5]:
print(arr)

[1 2 3 4]


In [6]:
l+10

TypeError: can only concatenate list (not "int") to list

In [7]:
arr+10

array([11, 12, 13, 14])

In [8]:
arr-10

array([-9, -8, -7, -6])

In [9]:
l * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [10]:
arr * 2

array([2, 4, 6, 8])

In [11]:
l ** 2 

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [12]:
arr ** 2 

array([ 1,  4,  9, 16], dtype=int32)

In [14]:
l1 = [1, 2, 3, "string_test", 1.1]

In [15]:
arr2 = np.array(l1)

In [16]:
print(arr2)

['1' '2' '3' 'string_test' '1.1']


In [17]:
range(1.5,10.5)

TypeError: 'float' object cannot be interpreted as an integer

In [20]:
arr3  = np.arange(1.5, 10.5, 0.2)

In [21]:
print(arr3)

[ 1.5  1.7  1.9  2.1  2.3  2.5  2.7  2.9  3.1  3.3  3.5  3.7  3.9  4.1
  4.3  4.5  4.7  4.9  5.1  5.3  5.5  5.7  5.9  6.1  6.3  6.5  6.7  6.9
  7.1  7.3  7.5  7.7  7.9  8.1  8.3  8.5  8.7  8.9  9.1  9.3  9.5  9.7
  9.9 10.1 10.3]


In [25]:
arr4 = np.arange(1,11, 0.1)

In [26]:
print(arr4)

[ 1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3
  2.4  2.5  2.6  2.7  2.8  2.9  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7
  3.8  3.9  4.   4.1  4.2  4.3  4.4  4.5  4.6  4.7  4.8  4.9  5.   5.1
  5.2  5.3  5.4  5.5  5.6  5.7  5.8  5.9  6.   6.1  6.2  6.3  6.4  6.5
  6.6  6.7  6.8  6.9  7.   7.1  7.2  7.3  7.4  7.5  7.6  7.7  7.8  7.9
  8.   8.1  8.2  8.3  8.4  8.5  8.6  8.7  8.8  8.9  9.   9.1  9.2  9.3
  9.4  9.5  9.6  9.7  9.8  9.9 10.  10.1 10.2 10.3 10.4 10.5 10.6 10.7
 10.8 10.9]


In [27]:
len(arr4)

100

In [28]:
arr5 = np.linspace(1,10,100)

In [29]:
print(arr5)

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

In [30]:
len(arr5)

100

In [4]:
arry_of_zeros = np.zeros((2,3))
arry_of_zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arr_of_ones = np.ones((2,3,4))
arr_of_ones


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [7]:
arr_linspace = np.linspace(0,2,9)
arr_linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [8]:
#each element of same value example below is 7# sh
arr_full = np.full((2,2),7)
arr_full

array([[7, 7],
       [7, 7]])

In [9]:
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [11]:
r = np.random.random((2,2))
r

array([[0.6768383 , 0.53027888],
       [0.04287451, 0.26365433]])

In [13]:
r1 = np.random.rand(2,2)
r1

array([[0.76480432, 0.40153188],
       [0.77322874, 0.66810194]])

In [14]:
r2 = np.random.randn(2,2)
r2
#include negative values 

array([[ 1.03411776, -1.38742083],
       [ 0.78018766, -0.94874565]])

In [18]:
#only specific range 40, 50
r3  = np.random.randint(40,98,size=(5,5))
r3

array([[65, 40, 61, 70, 41],
       [96, 79, 73, 83, 91],
       [85, 89, 40, 69, 54],
       [85, 58, 54, 75, 50],
       [41, 90, 95, 57, 53]])

In [19]:
#only specific range 40, 50
r4  = np.random.randint(40,98,size=(1000,20))
r4

array([[42, 70, 48, ..., 74, 78, 44],
       [90, 41, 92, ..., 48, 91, 86],
       [72, 61, 41, ..., 56, 81, 77],
       ...,
       [87, 78, 91, ..., 51, 93, 72],
       [55, 62, 69, ..., 74, 68, 74],
       [53, 84, 83, ..., 76, 83, 95]])

In [21]:
#choice function
r5 = np.random.choice(list("kris"))
r5

'k'

In [23]:
#shuffle function change the positions
np.random.shuffle(r3)
r3

array([[41, 90, 95, 57, 53],
       [96, 79, 73, 83, 91],
       [85, 58, 54, 75, 50],
       [85, 89, 40, 69, 54],
       [65, 40, 61, 70, 41]])